name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pill_pal_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.1-otp-27'
          otp-version: '27'

      - name: Install dependencies
        run: mix deps.get

      - name: Check code formatting
        run: mix format --check-formatted

      - name: Set up database
        run: mix ecto.create && mix ecto.migrate
        env:
          MIX_ENV: test
          DATABASE_URL: ecto://postgres:postgres@localhost/pill_pal_test

      - name: Run tests
        run: mix test
